/**
 * @copyright 2026 Jouni Sipola by OQM. All rights reserved.
 * Permission granted for personal/internal use only. Commercial
 * use prohibited except by copyright holder. See LICENSE for details.
 */

/**
 * @description TypeScript interfaces for the trainee feature (OQM-0014).
 *   @see skills/SKILL.wire-react-to-gas.md
 *   @see skills/SKILL.sheet-schema.md
 */

/**
 * Payload for registering a trainee PIN code.
 * Maps to the registerTraineePin GAS backend route.
 * @see skills/SKILL.wire-react-to-gas.md
 */
export interface RegisterTraineePinData {
  /** Trainee's first name (required). */
  firstname: string;
  /** Trainee's last name (required). */
  lastname: string;
  /** Trainee's age as a string (required by the current GAS contract). */
  age: string;
  /** Numeric PIN string to register (required). */
  pin: string;
}

/**
 * Trainee data returned by registerTraineePin and verifyTraineePin.
 * @see skills/SKILL.wire-react-to-gas.md
 */
export interface TraineeData {
  /** Stable row UUID generated by the backend. */
  id: string;
  /** Trainee's first name. */
  firstname: string;
  /** Trainee's last name. */
  lastname: string;
  /** Trainee's age as stored in trainee_login. */
  age: string;
  /** Registered PIN code. */
  pin: string;
  /** ISO-8601 creation timestamp. */
  created_at: string;
  /** ISO-8601 last activity timestamp, empty until first use. */
  last_activity: string;
}

/**
 * Payload for registering a trainee for a specific session.
 * Maps to the registerTraineeForSession GAS backend route.
 * @see skills/SKILL.wire-react-to-gas.md
 */
export interface RegisterTraineeForSessionPayload {
  /** Trainee's first name (required). */
  first_name: string;
  /** Trainee's last name (required). */
  last_name: string;
  /** 'adult' or 'underage' (required). */
  age_group: 'adult' | 'underage';
  /** Trainee's age — required when age_group is 'underage'. */
  underage_age?: number;
  /** Session type the trainee is registering to (required). */
  session_type: string;
  /** ID from camp_schedules sheet, or omitted for non-camp sessions. */
  camp_session_id?: string;
  /** Date in 'YYYY-MM-DD' format (required). */
  date: string;
  /** Start time in 'HH:MM' format (required). */
  start_time: string;
  /** End time in 'HH:MM' format (required). */
  end_time: string;
}

/**
 * Session item returned for trainee registration page.
 * @see skills/SKILL.wire-react-to-gas.md
 */
export interface TraineeSessionItem {
  /** Unique identifier based on source row + date. */
  id: string;
  /** English session type key/name. */
  session_type: string;
  /** Localized display name for session type. */
  session_type_alias: string;
  /** Date in 'YYYY-MM-DD' format. */
  date: string;
  /** Start time in 'HH:MM' format. */
  start_time: string;
  /** End time in 'HH:MM' format. */
  end_time: string;
  /** Session location, empty string when unknown. */
  location: string;
  /** Coach first name for free/sparring sessions, otherwise empty. */
  coach_firstname: string;
  /** Coach last name for free/sparring sessions, otherwise empty. */
  coach_lastname: string;
  /** Camp instructor name for camp sessions, otherwise empty. */
  camp_instructor_name: string;
  /** True when session_type is free/sparring. */
  is_free_sparring: boolean;
  /** Frontend-only flag for visualizing registered sessions. */
  trainee_registered?: boolean;
}

/**
 * Pending trainee profile data persisted on Trainee page after a successful registration.
 */
export interface PendingTraineeData {
  first_name: string;
  last_name: string;
  age_group: 'adult' | 'underage';
  underage_age?: number;
}

/**
 * Optional identity context sent when fetching trainee sessions.
 * When provided, backend marks matching sessions as trainee_registered.
 */
export interface TraineeSessionIdentityPayload {
  first_name: string;
  last_name: string;
  age_group: 'adult' | 'underage';
  underage_age?: number;
}
